baseURL = "https://https://yeshavantakp-leilani.github.io/village-news/"
languageCode = "en"
title = "NRIs of Sagar"
theme = "Mainroad"

[languages]
  [languages.en]
    weight = 1
    languageName = "English"

  [languages.kn]
    weight = 2
    languageName = "ಕನ್ನಡ"

[params]
  mainSections = ["events"]

[markup.goldmark.renderer]
  unsafe = true